# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: ./ # Use an image built from the specified dockerfile in the `app-server` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container (docker) to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/storm121
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks: # Networks to join (Services on the same network can communicate with each other using their name and no need of address)
      - backend
      - frontend
  # Frontend Service
  client:
    build:
      context: src/webapp/storm121
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "9090:80" # Map the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - server
    networks:
      - frontend
  # Database Service (Mysql)
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: storm121
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes: # volumes could help in case we lost stored data (it persist data in host machine in the db-data directory)
      - db-data:/var/lib/mysql
    networks:
      - backend
# Define Volumes to be created
volumes:
  db-data:
# Define Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: